cabal-version:   3.4
name:            kotiba
version:         0.1.0.0
homepage:        https://kotiba.app.xinux.uz
license:         AGPL-3.0-or-later
license-file:    LICENSE
author:          lambdajon
maintainer:      lambdajon42@gmail.com
category:        Network
build-type:      Simple
extra-doc-files: CHANGELOG.md

common warnings
  ghc-options: -Wall -Wunused-imports

library
  import:             warnings
  hs-source-dirs:     src
  exposed-modules:
    Forgejo
    Forgejo.API
    Forgejo.API.CommitStatus
    Forgejo.API.OrgMembers
    Forgejo.API.PullRequest
    Forgejo.App
    Forgejo.Methods.CommitStatus
    Forgejo.Methods.OrgMembers
    Forgejo.Methods.PullRequest
    Forgejo.Types.ActionRun
    Forgejo.Types.Comment
    Forgejo.Types.Commit
    Forgejo.Types.Common
    Forgejo.Types.Event
    Forgejo.Types.EventType
    Forgejo.Types.Issue
    Forgejo.Types.IssueComment
    Forgejo.Types.PullRequest
    Forgejo.Types.Push
    Forgejo.Types.Repository
    Forgejo.Types.User
    Forgejo.Update
    Forgejo.Webhook
    Kotiba
    Kotiba.API
    Kotiba.API.Util
    Kotiba.Config
    Kotiba.Database
    Kotiba.Prelude
    Kotiba.Server

  build-depends:
    , aeson
    , base
    , bytestring
    , conduit
    , conduit-combinators
    , containers
    , esqueleto
    , filepath
    , generic-lens
    , http-api-data
    , http-client-tls
    , http-media
    , http-types
    , lens
    , monad-logger
    , mtl
    , named
    , optparse-generic
    , path-pieces
    , persistent
    , persistent-postgresql
    , resource-pool
    , safe-exceptions
    , servant-client
    , servant-client-core
    , servant-server
    , stm
    , text
    , time
    , toml-parser
    , transformers
    , uuid
    , vector
    , wai
    , wai-extra
    , warp

  default-language:   GHC2024
  default-extensions:
    BlockArguments
    DataKinds
    DeriveAnyClass
    DerivingStrategies
    ImplicitParams
    ImportQualifiedPost
    LambdaCase
    OverloadedRecordDot
    RecordWildCards

executable kotiba
  import:           warnings
  ghc-options:      -threaded -rtsopts -with-rtsopts=-N
  main-is:          Main.hs
  hs-source-dirs:   app
  build-depends:
    , base
    , kotiba

  default-language: GHC2021

test-suite kotiba-test
  import:           warnings
  type:             exitcode-stdio-1.0
  main-is:          Main.hs
  hs-source-dirs:   test
  build-depends:
    , base
    , hspec
    , hspec-wai
    , kotiba

  default-language: GHC2021
