cabal-version:   3.4
name:            kotiba
version:         0.1.0.0
homepage:        https://kotiba.app.xinux.uz
license:         AGPL-3.0-or-later
license-file:    LICENSE
author:          lambdajon
maintainer:      lambdajon42@gmail.com
category:        Network
build-type:      Simple
extra-doc-files: CHANGELOG.md

common warnings
  ghc-options: -Wall -Wunused-imports -threaded

library
  import:             warnings
  hs-source-dirs:     src
  exposed-modules:
    API
    API.Dev
    API.Util
    Config
    Database
    Database.Types
    Events.Backport
    Events.PullRequest
    Git.Backport
    Git.Core
    Git.PullRequest
    Kotiba.Prelude
    Server

  build-depends:
    , aeson
    , base
    , bytestring
    , conduit
    , conduit-combinators
    , containers
    , directory
    , esqueleto
    , filepath
    , forgejo
    , generic-lens
    , http-api-data
    , http-client-tls
    , http-media
    , http-types
    , lens
    , monad-logger
    , mtl
    , named
    , optparse-generic
    , path-pieces
    , persistent
    , persistent-postgresql
    , persistent-records
    , random
    , resource-pool
    , safe-exceptions
    , servant-client
    , servant-client-core
    , servant-server
    , shower
    , stm
    , text
    , time
    , toml-parser
    , transformers
    , typed-process
    , uuid
    , vector
    , wai
    , wai-extra
    , warp

  default-language:   GHC2024
  default-extensions:
    BlockArguments
    DataKinds
    DeriveAnyClass
    DerivingStrategies
    ImplicitParams
    ImportQualifiedPost
    LambdaCase
    OverloadedRecordDot
    RecordWildCards

executable kotiba
  import:           warnings
  ghc-options:      -threaded -rtsopts -with-rtsopts=-N
  main-is:          Main.hs
  hs-source-dirs:   app
  build-depends:
    , base
    , kotiba

  default-language: GHC2021

test-suite kotiba-test
  import:           warnings
  type:             exitcode-stdio-1.0
  main-is:          Main.hs
  hs-source-dirs:   test
  build-depends:
    , base
    , hspec
    , hspec-wai
    , kotiba

  default-language: GHC2021
