name: Test CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test-flake:
    name: "Test flake"
    runs-on: native

    steps:
      - name: Clone the repository
        uses: actions/checkout@v6

      - name: Check up flake configuration
        run: nix flake check --show-trace

  build-project:
    name: "Build Project"
    runs-on: native

    steps:
      - name: Clone the repository
        uses: actions/checkout@v6

      - name: Build NixOS configuration
        run: nix build
